-- Phase 15: Study Tools (Notes & Glossary)

-- 1. Table: Personal Notes (Private per user per class)
CREATE TABLE public.personal_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    clase_id BIGINT REFERENCES public.clases_generadas(id) ON DELETE CASCADE NOT NULL,
    content TEXT DEFAULT '',
    UNIQUE(user_id, clase_id) -- Only one note pad per class per user
);

-- 2. Table: Glossary Terms (Collaborative)
CREATE TABLE public.glossary_terms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    clase_id BIGINT REFERENCES public.clases_generadas(id) ON DELETE CASCADE,
    term TEXT NOT NULL,
    definition TEXT NOT NULL,
    likes_count INTEGER DEFAULT 0
);

-- 3. RLS
ALTER TABLE public.personal_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.glossary_terms ENABLE ROW LEVEL SECURITY;

-- 4. Policies: Personal Notes
-- Users can only see/edit their own notes
CREATE POLICY "My Notes Select" ON public.personal_notes FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "My Notes Insert" ON public.personal_notes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "My Notes Update" ON public.personal_notes FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "My Notes Delete" ON public.personal_notes FOR DELETE USING (auth.uid() = user_id);

-- 5. Policies: Glossary
-- Everyone can read
CREATE POLICY "Glossary Public Read" ON public.glossary_terms FOR SELECT USING (true);
-- Auth users can insert
CREATE POLICY "Glossary Auth Insert" ON public.glossary_terms FOR INSERT WITH CHECK (auth.uid() = user_id);
-- Only owner can edit/delete (or admin, skipping admin logic for now)
CREATE POLICY "Glossary Owner Update" ON public.glossary_terms FOR UPDATE USING (auth.uid() = user_id);

-- 6. Trigger for updated_at on notes
CREATE OR REPLACE FUNCTION public.handle_notes_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_notes_updated
    BEFORE UPDATE ON public.personal_notes
    FOR EACH ROW EXECUTE PROCEDURE public.handle_notes_updated_at();
