-- Phase 14 Part 2: Contributions & Activity Feed

-- 1. Table: Contributions (Aportes de la comunidad)
CREATE TABLE public.contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    clase_id BIGINT REFERENCES public.clases_generadas(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content TEXT NOT NULL, -- Markdown supported
    likes_count INTEGER DEFAULT 0,
    is_approved BOOLEAN DEFAULT TRUE -- Auto-approve for now, can moderate later
);

-- 2. Table: Activity Feed (Global or Friends)
CREATE TABLE public.activity_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL, -- 'completed_class', 'earned_badge', 'published_contribution'
    metadata JSONB, -- Stores { title: "Algebra 1", url: "/clase/123" }
    is_public BOOLEAN DEFAULT TRUE
);

-- 3. RLS
ALTER TABLE public.contributions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_log ENABLE ROW LEVEL SECURITY;

-- 4. Policies
CREATE POLICY "Public Read Contributions" ON public.contributions FOR SELECT USING (true);
CREATE POLICY "Auth Insert Contributions" ON public.contributions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Owner Update Contributions" ON public.contributions FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Public Read Activity" ON public.activity_log FOR SELECT USING (is_public = true);
-- Only system/triggers usually insert activity, or user actions via functions.
-- Let's allow users to read only. Insertion via triggers/functions preferred.
-- But for simplicity, let auth consumers insert if they trigger it (e.g. client side validation... wait, risky).
-- Better: Use Triggers.

-- 5. Trigger: Log Class Completion
CREATE OR REPLACE FUNCTION public.log_class_completion()
RETURNS TRIGGER AS $$
DECLARE
    class_title TEXT;
BEGIN
    IF NEW.completado = TRUE AND (OLD.completado = FALSE OR OLD.completado IS NULL) THEN
        SELECT tema INTO class_title FROM public.clases_generadas WHERE id = NEW.clase_id;
        
        INSERT INTO public.activity_log (user_id, action_type, metadata)
        VALUES (
            NEW.user_id, 
            'completed_class', 
            jsonb_build_object('title', class_title, 'class_id', NEW.clase_id)
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_class_completed
    AFTER INSERT OR UPDATE ON public.clases_progreso
    FOR EACH ROW EXECUTE PROCEDURE public.log_class_completion();

-- 6. Trigger: Log New Contribution
CREATE OR REPLACE FUNCTION public.log_contribution()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.activity_log (user_id, action_type, metadata)
    VALUES (
        NEW.user_id, 
        'published_contribution', 
        jsonb_build_object('title', NEW.title, 'id', NEW.id)
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_contribution_created
    AFTER INSERT ON public.contributions
    FOR EACH ROW EXECUTE PROCEDURE public.log_contribution();
