-- Phase 13: Hierarchical Structure (Platzi Style)

-- 1. Table: Escuelas (e.g., "Escuela de Matemáticas", "Escuela de Tecnología")
CREATE TABLE public.escuelas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    icon_url TEXT, -- URL to an SVG or PNG icon
    color TEXT DEFAULT '#99f6e4' -- Hex color for UI branding
);

-- 2. Table: Rutas (e.g., "Ruta de Álgebra", "Ruta de Desarrollo Web")
CREATE TABLE public.rutas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    escuela_id BIGINT REFERENCES public.escuelas(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    icon_url TEXT,
    level TEXT DEFAULT 'Básico' -- Básico, Intermedio, Avanzado
);

-- 3. Table: Cursos (e.g., "Curso de Álgebra Lineal", "Curso de HTML5")
CREATE TABLE public.cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ruta_id BIGINT REFERENCES public.rutas(id) ON DELETE SET NULL, -- A course might belong to multiple routes conceptually, but for now 1:N
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    image_url TEXT, -- Cover image for the course card
    instructor TEXT DEFAULT 'Profe INEA'
);

-- 4. Junction Table for Many-to-Many: Rutas <-> Cursos (Optional but better)
-- Ideally a course can be in multiple paths. Let's create a junction table.
CREATE TABLE public.ruta_cursos (
    ruta_id BIGINT REFERENCES public.rutas(id) ON DELETE CASCADE,
    curso_id BIGINT REFERENCES public.cursos(id) ON DELETE CASCADE,
    "order" INTEGER DEFAULT 0, -- Order of the course within the path
    PRIMARY KEY (ruta_id, curso_id)
);

-- 5. Modify 'clases_generadas' to belong to a 'curso'
-- We add 'curso_id' column. Existing classes will need to be migrated or assigned 'null' initially.
ALTER TABLE public.clases_generadas 
ADD COLUMN IF NOT EXISTS curso_id BIGINT REFERENCES public.cursos(id) ON DELETE SET NULL;

ALTER TABLE public.clases_generadas 
ADD COLUMN IF NOT EXISTS "order" INTEGER DEFAULT 0; -- Order of the class in the course

-- 6. Enable RLS (Row Level Security)
ALTER TABLE public.escuelas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rutas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cursos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ruta_cursos ENABLE ROW LEVEL SECURITY;

-- 7. Policies (Public Read, Admin Write)
CREATE POLICY "Public Read Escuelas" ON public.escuelas FOR SELECT USING (true);
CREATE POLICY "Public Read Rutas" ON public.rutas FOR SELECT USING (true);
CREATE POLICY "Public Read Cursos" ON public.cursos FOR SELECT USING (true);
CREATE POLICY "Public Read RutaCursos" ON public.ruta_cursos FOR SELECT USING (true);

-- (Assuming authenticated admins have specific roles, or for now just allow public read)

-- 8. Seed Data (Initial Structure)
INSERT INTO public.escuelas (name, slug, description, color) VALUES
('Escuela de Ciencias', 'ciencias', 'Domina la física, química y biología.', '#10b981'),
('Escuela de Matemáticas', 'matematicas', 'Desde aritmética básica hasta cálculo.', '#3b82f6'),
('Escuela de Lenguaje', 'lenguaje', 'Mejora tu lectura, escritura y comunicación.', '#f59e0b');

-- 9. Function to get full hierarchy (Optional optimization)
CREATE OR REPLACE FUNCTION get_full_hierarchy()
RETURNS JSONB AS $$
DECLARE
    result JSONB;
BEGIN
    SELECT jsonb_agg(
        jsonb_build_object(
            'id', e.id,
            'name', e.name,
            'slug', e.slug,
            'rutas', (
                SELECT jsonb_agg(
                    jsonb_build_object(
                        'id', r.id,
                        'name', r.name,
                        'slug', r.slug,
                        'cursos', (
                            SELECT jsonb_agg(
                                jsonb_build_object(
                                    'id', c.id,
                                    'name', c.name,
                                    'slug', c.slug,
                                    'image', c.image_url
                                ) ORDER BY rc."order" ASC
                            )
                            FROM public.ruta_cursos rc
                            JOIN public.cursos c ON c.id = rc.curso_id
                            WHERE rc.ruta_id = r.id
                        )
                    )
                )
                FROM public.rutas r
                WHERE r.escuela_id = e.id
            )
        )
    ) INTO result
    FROM public.escuelas e;
    
    RETURN result;
END;
$$ LANGUAGE plpgsql;
