-- Phase 16: Live & Events

-- 1. Enum for Event Status
DO $$ BEGIN
    CREATE TYPE event_status AS ENUM ('scheduled', 'live', 'ended');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Table: Events
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ,
    stream_url TEXT, -- YouTube Video ID or URL
    status event_status DEFAULT 'scheduled',
    instructor_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table: Event Chat Messages (Linear Chat for Live Stream)
CREATE TABLE IF NOT EXISTS public.event_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES public.events(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. RLS
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_chat_messages ENABLE ROW LEVEL SECURITY;

-- 5. Policies: Events
-- Public Read
CREATE POLICY "Events Public Read" ON public.events FOR SELECT USING (true);
-- Only authenticated users can insert (restricted to admins in real app, but ok for MVP)
CREATE POLICY "Events Admin Insert" ON public.events FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Events Admin Update" ON public.events FOR UPDATE USING (auth.role() = 'authenticated');

-- 6. Policies: Chat
-- Public can read chat
CREATE POLICY "Chat Public Read" ON public.event_chat_messages FOR SELECT USING (true);
-- Authenticated users can post
CREATE POLICY "Chat Auth Insert" ON public.event_chat_messages FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 7. Realtime
-- Enable Realtime for Chat to work efficiently
ALTER PUBLICATION supabase_realtime ADD TABLE public.event_chat_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.events;

-- 8. Seed Data (One Live Event, One Scheduled)
INSERT INTO public.events (title, description, start_time, stream_url, status, instructor_name)
VALUES 
('Clase Magna de Matemáticas', 'Resolviendo ecuaciones en vivo con el Profe Alex.', NOW(), 'dQw4w9WgXcQ', 'live', 'Profe Alex'),
('Taller de Lectura Rápida', 'Técnicas avanzadas para leer un libro al día.', NOW() + INTERVAL '1 day', NULL, 'scheduled', 'Lic. Maria')
ON CONFLICT DO NOTHING;
